name: Common Frontend Tests
on:
  pull_request:
    paths:
      - components/crud-web-apps/common/frontend/kubeflow-common-lib/**
      - releasing/version/VERSION
    branches:
      - main
      - v*-branch
      - notebooks-v1

env:
  NODE_VERSION: 24.11.1
  FRONTEND_DIR: components/crud-web-apps/common/frontend/kubeflow-common-lib

jobs:
  frontend-format-lint-check:
    name: Check code format and lint
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ${{ env.FRONTEND_DIR }} 

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Check frontend code formatting
        run: npm run format:check

      - name: Check frontend code linting
        run: npm run lint-check

  frontend-unit-tests:
    runs-on: ubuntu-22.04
    name: Unit tests
    defaults:
      run:
        working-directory: ${{ env.FRONTEND_DIR }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Kubeflow common library dependencies
        run: npm ci

      - name: Run unit tests
        run: npm run test:prod